/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnixUtilities */

#ifndef _Included_UnixUtilities
#define _Included_UnixUtilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnixUtilities
 * Method:    ipconfig
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_UnixUtilities_ipconfig
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
